services:
  postgres:
    image: postgres:16-alpine
    container_name: nauthenticity_postgres
    restart: 'no'
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - nauthenticity_network
      - shared-mesh
    labels:
      - 'traefik.enable=true'
      - 'traefik.tcp.routers.nauthenticity-postgres.rule=HostSNI(`postgres.nauthenticity.localhost`)'
      - 'traefik.tcp.routers.nauthenticity-postgres.entrypoints=postgres'
      - 'traefik.tcp.routers.nauthenticity-postgres.tls=true'
      - 'traefik.tcp.services.nauthenticity-postgres.loadbalancer.server.port=5432'
      - 'traefik.docker.network=shared-mesh'

  redis:
    image: redis:7-alpine
    container_name: nauthenticity_redis
    restart: 'no'
    networks:
      - nauthenticity_network
      - shared-mesh
    labels:
      - 'traefik.enable=true'
      - 'traefik.tcp.routers.nauthenticity-redis.rule=HostSNI(`redis.nauthenticity.localhost`)'
      - 'traefik.tcp.routers.nauthenticity-redis.entrypoints=redis'
      - 'traefik.tcp.routers.nauthenticity-redis.tls=true'
      - 'traefik.tcp.services.nauthenticity-redis.loadbalancer.server.port=6379'
      - 'traefik.docker.network=shared-mesh'

  app:
    build: .
    container_name: nauthenticity
    restart: 'no'
    environment:
      - PORT=${PORT:-3000}
      - NODE_ENV=${NODE_ENV:-development}
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@postgres:5432/${DB_NAME}?schema=public
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - APIFY_TOKEN=${APIFY_TOKEN}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - TRANSCRIPTION_URL=http://shared_whisper:8000
    volumes:
      - ./storage:/app/storage
    # ports:
    #   - '3000:3000'
    networks:
      - nauthenticity_network
      - shared-mesh
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.nauthenticity.rule=Host(`nauthenticity.localhost`) || Host(`nauthenticity.9nau.com`)'
      - 'traefik.http.routers.nauthenticity.entrypoints=web'
      - 'traefik.http.services.nauthenticity.loadbalancer.server.port=3000'
      - 'traefik.docker.network=shared-mesh'

networks:
  nauthenticity_network:
    driver: bridge
  shared-mesh:
    external: true

volumes:
  postgres_data:
